ualibweb/roots-ualib

- templates/header.php
Per [Michael Pearce's KACE ticket](https://kace.oit.ua.edu/adminui/ticket?ID=28161), I've updated the org chart in the header/navbar.
> dev build: updated header html

- base.php
Another ACF array conditional update, this time for the submenus on some pages.
> update template conditional for ACF submenu

- intranet/inc/tech-request-form-result.php
- intranet/inc/tech-request-form.php
Emails were including html encoding for apostrophes, so I decoded them and striped weird slashes (thanks, php). 
I also updated the form fields based on feedback from Danny.
> Tech request update

- intranet/inc/dest/tech-request-form-result.php
- intranet/inc/tech-request-form.php
Closed PR #60 in favor of a fresh start.
Original PR message:
> I hate to open a PR for such a small thing, but I didn't realize WP nicename and display name were so different until I had it up on dev. Fixed! 👍
But then I realized I hadn't run the live-build to replace the code in that grunt builds for the live version, so I did that, too. Not a waste after all! 🙌
> Update tech request form requester field

- assets/js/covidCounter.js
- functions-ualib.php
add counter script; update script enqueue conditional
I added a new page for testing: https://wwwdev2.lib.ua.edu/covid-counter
> Add building capacity counter

- functions-ualib.php
There was an error with calling the same script twice; removed it from `functions-ualib.php`
> removed script conditional

- templates/header.php
Updating link to org chart per Michael Pearce request (KACE ticket 29354)
> update org chart link

- templates/footer.php
updated links in footer as requested by AD Wilson
> footer updates

- templates/header.php
Reverts ualibweb/roots-ualib#89
> Revert "implemented changes to header mega menu per AD"

- templates/footer.php
Reverts ualibweb/roots-ualib#87
> Revert "footer updates"

- templates/footer.php
- templates/header.php
Updates to mega menu and footer as requested by AD Tom Wilson in the website changes doc.
> James megamenu footer updates

- templates/header.php
Swapped two submenu items to fix whitespace issue.
> swapped two submenu items to reduce irritating whitespace issue

- intranet/inc/dest/studentemployeerequest-result.php
- intranet/inc/incidentreport-result.php
- intranet/inc/studentemployeerequest-result.php
Updated email addresses in two intranet forms - Student Employee Job Request Form and Incident Report Form - as requested by Amy Wilson in [KACE ticket 29708](https://kace.oit.ua.edu/adminui/ticket.php?ID=29708).
> updated intranet forms per KACE ticket 29708

- intranet/inc/incidentreport-result.php
Added Kara Gibson as incident report recipient per [KACE ticket 29787](https://kace.oit.ua.edu/adminui/ticket.php?ID=29787)
> added Kara Gibson as recipient per KACE ticket 29787 (Tom Wilson)

- templates/header.php
per request from Karen Chapman
> added back link to group study rooms in megamenu

- intranet/inc/dest/tech-request-form-result.php
- intranet/inc/tech-request-form-result.php
added check for file size of zero (no file uploaded)
> allow TRF to be submitted without an image

- intranet/inc/circ-trace-form-result.php
- intranet/inc/dest/circ-trace-form-result.php
Replaced Jaiva Bonner with Matthew Miller ([KACE ticket 31007](https://kace.oit.ua.edu/adminui/ticket.php?ID=31007))
> updated email recipients per C. Davis KACE #31007

- templates/header.php
per KACE ticket [31128](https://kace.oit.ua.edu/adminui/ticket.php?ID=31128) (Kevin Walker)
> updated Research Data Services link in mega menu

- templates/header.php
updated the link and link text in About > Libraries Locations
> dev build: header updates - Annex is now Archival Facility

- intranet/inc/circ-trace-form-result.php
- intranet/inc/dest/circ-trace-form-result.php
Changed recipients of circ trace form per request by Cornelia Davis ([JIRA ticket WS-19](https://jirauaedu.atlassian.net/browse/WS-21))
> james - changed recipients of circ trace form

- intranet/inc/incidentreport-result.php
[Jira Ticket WS-125](https://jirauaedu.atlassian.net/browse/WS-125)
> replaced Lane Weaver with Tyler Capell

- templates/header.php
[Jira WS-110](https://jirauaedu.atlassian.net/browse/WS-110)
> james - added faculty committees page link to mega menu
